//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Martial_Arts_Price.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string Image { get; set; }
        public byte[] ImageUpload { get; set; }
        public string Info { get; set; }
        public int StyleID { get; set; }
        public int TeacherID { get; set; }
        public Nullable<decimal> Price { get; set; }
    
        public virtual Style Style { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
